### PR TITLE
multiple items to be checked out at once w/ different due dates

### PR DESCRIPTION
**Pull request by ehf5307**
changes to models to allow for multiple items to be checked out at one time and to have different due dates

### CODE REVIEW

**Comment by Awmusic12635** [comment]
The build is failing because you have class CheckoutItem defined before Checkout is defined. And you have  foreign key on CheckoutItem for:  

`checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE) `

that references Checkout. I do not think there needs to be a foreign key for checkout on checkoutitem. We already have the reference from the checkout itself which items are in it.

**Review by Awmusic12635 — CHANGES_REQUESTED** [review]
The build is failing because you have class CheckoutItem defined before Checkout is defined. And you have foreign key on CheckoutItem for:

checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE)

that references Checkout. I do not think there needs to be a foreign key for checkout on checkoutitem. We already have the reference from the checkout itself which items are in it.

**Comment by ehf5307** [comment]
Thats how the many to many fields with the 'through' option works though.
Remember this is djangos stupid implementation of a database that doesnt do
things normally.

**Comment by Awmusic12635** [comment]
Looks like we are both half right on this one. My correction was not fully right, but the relationship I believe is a one to many and not a many to many. Because a checkout can have many checkoutitems but a checkout item cannot belong to many checkouts.

I believe taking 

`checkOutItems = models.ManyToManyField(Item, through='CheckoutItem')`

deleting out of Checkout and then moving checkout to be defined above CheckoutItem will fix the issue. 

This will let us do thing like: 

`checkout.checkoutitem_set.all()`

To get all the checkout items later down the line.

**Comment by ehf5307** [comment]
Right. Okay ill make those changes.

**Review by Awmusic12635 — APPROVED** [review]

**Pull request merged**
